import LOGO_TECH_1TX_URL from 'public/images/tech_1tx.png';
import STAR1_URL from 'public/images/star1.png';
import STAR2_URL from 'public/images/star2.png';
import TOKEN_PIXEL_1_URL from 'public/images/token_pixel_1.png';
import TOKEN_PIXEL_2_URL from 'public/images/token_pixel_2.png';
import TOKEN_PIXEL_3_URL from 'public/images/token_pixel_3.png';
import TOKEN_PIXEL_4_URL from 'public/images/token_pixel_4.png';
import TOKEN_PIXEL_5_URL from 'public/images/token_pixel_5.png';
import TOKEN_PIXEL_6_URL from 'public/images/token_pixel_6.png';
import TOKEN_PIXEL_7_URL from 'public/images/token_pixel_7.png';
import TOKEN_PIXEL_8_URL from 'public/images/token_pixel_8.png';
import TOKEN_PIXEL_9_URL from 'public/images/token_pixel_9.png';
import LOGO_FULL_URL from 'public/images/logo_full.png';
import LOGO_SHORT_URL from 'public/images/logo_short.png';

export const LOGO_TECH_1TX = LOGO_TECH_1TX_URL;
export const STAR_1 = STAR1_URL;
export const STAR_2 = STAR2_URL;
export const TOKEN_PIXEL_1 = TOKEN_PIXEL_1_URL;
export const TOKEN_PIXEL_2 = TOKEN_PIXEL_2_URL;
export const TOKEN_PIXEL_3 = TOKEN_PIXEL_3_URL;
export const TOKEN_PIXEL_4 = TOKEN_PIXEL_4_URL;
export const TOKEN_PIXEL_5 = TOKEN_PIXEL_5_URL;
export const TOKEN_PIXEL_6 = TOKEN_PIXEL_6_URL;
export const TOKEN_PIXEL_7 = TOKEN_PIXEL_7_URL;
export const TOKEN_PIXEL_8 = TOKEN_PIXEL_8_URL;
export const TOKEN_PIXEL_9 = TOKEN_PIXEL_9_URL;
export const LOGO_FULL = LOGO_FULL_URL;
export const LOGO_SHORT = LOGO_SHORT_URL;
