import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Image from 'next/image';
import Script from 'next/script';
import Container from 'src/components/container/container';
import Header from 'src/components/layout/header/header';
import ProviderEVM from 'src/components/providerEVM/providerEVM';
import { TOKEN_PIXEL_1, TOKEN_PIXEL_2, TOKEN_PIXEL_3, TOKEN_PIXEL_4, TOKEN_PIXEL_5, TOKEN_PIXEL_6, TOKEN_PIXEL_7, TOKEN_PIXEL_8, TOKEN_PIXEL_9 } from 'src/constants/ImagePath';
import 'src/styles/index.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <Script
                    dangerouslySetInnerHTML={{
                        __html: `
                            (function() {
                                try {
                                    const stored = localStorage.getItem('theme');
                                    const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
                                    // Default to dark if no stored preference
                                    const isDark = stored ? (stored === '"dark"' || stored === 'dark') : prefersDark || true;
                                    if (isDark) document.documentElement.classList.add('dark');
                                    else document.documentElement.classList.remove('dark');
                                } catch (e) {}
                            })();
                        `,
                    }}
                />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ProviderEVM>
                    <div className="relative h-fit bg-[#0A0A0A] min-h-screen overflow-hidden">
                        <div className="fixed top-0 z-50 w-full">
                            <Header />
                        </div>
                        <div className="z-0 absolute top-0 h-[800px] w-full bg-[linear-gradient(to_bottom,#0A0A0A_0%,#450822_60%,#6B2E48_80%,#8F3D61_100%)]">
                            <div className="absolute inset-0 bg-cover bg-no-repeat mix-blend-overlay h-[1080px] -top-[280px]" style={{ backgroundImage: "url('/images/bg_unihybrid.png')" }}></div>
                        </div>
                        <div className="z-0 absolute top-[800px] h-[800px] w-full bg-[linear-gradient(to_top,#0A0A0A_0%,#450822_60%,#6B2E48_80%,#8F3D61_100%)]">
                            <div className="absolute inset-0 bg-cover bg-no-repeat mix-blend-overlay h-[800px] top-0" style={{ backgroundImage: "url('/images/bg_unihybrid_2.png')" }}></div>
                        </div>
                        <div className="relative z-1 ">
                            <Container>{children}</Container>
                        </div>
                        <Image alt="token_pixel_1" src={TOKEN_PIXEL_1} className="absolute top-70 -left-16 opacity-40 z-0" />
                        <Image alt="token_pixel_2" src={TOKEN_PIXEL_2} className="absolute top-120 left-36 opacity-40 z-0 hidden lg:block" />
                        <Image alt="token_pixel_3" src={TOKEN_PIXEL_3} className="absolute top-10 left-70 opacity-40 z-0" />
                        <Image alt="token_pixel_4" src={TOKEN_PIXEL_4} className="absolute top-90 left-90 opacity-30 z-0 " />
                        <Image alt="token_pixel_5" src={TOKEN_PIXEL_5} className="absolute -top-10 right-140 opacity-40 z-0" />
                        <Image alt="token_pixel_6" src={TOKEN_PIXEL_6} className="absolute top-10 right-40 opacity-40 z-0" />
                        <Image alt="token_pixel_7" src={TOKEN_PIXEL_7} className="absolute top-75 right-140 opacity-40 z-0" />
                        <Image alt="token_pixel_9" src={TOKEN_PIXEL_8} className="absolute top-65 -right-18 opacity-40 z-0 " />
                        <Image alt="token_pixel_8" src={TOKEN_PIXEL_9} className="absolute top-140 right-60 z-0 hidden lg:block" />
                    </div>
                </ProviderEVM>
            </body>
        </html>
    );
}
