// Image path constants - auto-generated by CLI
export type ImagePaths = {
  lightMode: string;
  darkMode: string;
};

// Firebase Hosting URLs
export const baseImgUrl = 'https://crypto-images-4545f.web.app/images';
export const baseImgUrlToken = (nameToken: string) => baseImgUrl + '/token/' + nameToken + '.png';
export const baseImgUrlSystem = (nameSystem: string) => baseImgUrl + '/system/' + nameSystem + '.png';
export const baseImgUrlWallet = (nameWallet: string) => baseImgUrl + '/wallet/' + nameWallet + '.png';

// Icon name mapping - auto-generated by CLI
export const iconMap: Record<string, ImagePaths> = {
  // Token icons will be added here
  "ARB": {
    lightMode: baseImgUrlToken("ARB"),
    darkMode: baseImgUrlToken("ARB")
  },
  "BNB": {
    lightMode: baseImgUrlToken("BNB"),
    darkMode: baseImgUrlToken("BNB")
  },
  "BTC": {
    lightMode: baseImgUrlToken("BTC"),
    darkMode: baseImgUrlToken("BTC")
  },
  "DOGE": {
    lightMode: baseImgUrlToken("DOGE"),
    darkMode: baseImgUrlToken("DOGE")
  },
  "ETH": {
    lightMode: baseImgUrlToken("ETH"),
    darkMode: baseImgUrlToken("ETH")
  },
  "SOL": {
    lightMode: baseImgUrlToken("SOL-lightmode"),
    darkMode: baseImgUrlToken("SOL-darkmode")
  },
  "USDC": {
    lightMode: baseImgUrlToken("USDC"),
    darkMode: baseImgUrlToken("USDC")
  },
  "USDT": {
    lightMode: baseImgUrlToken("USDT"),
    darkMode: baseImgUrlToken("USDT")
  },
  "XRP": {
    lightMode: baseImgUrlToken("XRP-lightmode"),
    darkMode: baseImgUrlToken("XRP-darkmode")
  },

  // Wallet icons will be added here
  "Keplr": {
    lightMode: baseImgUrlWallet("Keplr"),
    darkMode: baseImgUrlWallet("Keplr")
  },
  "Leap": {
    lightMode: baseImgUrlWallet("Leap"),
    darkMode: baseImgUrlWallet("Leap")
  },
  "MetaMask": {
    lightMode: baseImgUrlWallet("MetaMask"),
    darkMode: baseImgUrlWallet("MetaMask")
  },
  "Owallet": {
    lightMode: baseImgUrlWallet("Owallet"),
    darkMode: baseImgUrlWallet("Owallet")
  },
  "Phantom": {
    lightMode: baseImgUrlWallet("Phantom"),
    darkMode: baseImgUrlWallet("Phantom")
  },
  "WalletConnect": {
    lightMode: baseImgUrlWallet("WalletConnect"),
    darkMode: baseImgUrlWallet("WalletConnect")
  },

  // System icons will be added here
  "Base": {
    lightMode: baseImgUrlSystem("Base"),
    darkMode: baseImgUrlSystem("Base")
  },
  "BSC": {
    lightMode: baseImgUrlSystem("BSC"),
    darkMode: baseImgUrlSystem("BSC")
  },
  "Ethereum": {
    lightMode: baseImgUrlSystem("Ethereum"),
    darkMode: baseImgUrlSystem("Ethereum")
  },
};

export function getIconPaths(name: string): ImagePaths | null {
  return iconMap[name] || null;
}
